### ISSUE TITLE
大佬，请教下如何通过大漠工具获取游戏进程句柄啊？

### ISSUE THREAD

**Issue by cwj24h** [HelloBush/Java_MHXYdemo#13]
期望您的回答，谢谢大佬

**Comment by BigCatMiaoMM** [comment]
代码里有不过不是大漠



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月3日(周六) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HelloBush/Java_MHXYdemo] 大佬，请教下如何通过大漠工具获取游戏进程句柄啊？ (Issue #13)




 
期望您的回答，谢谢大佬

**Comment by HelloBush** [comment]
> 期望您的回答，谢谢大佬



> 期望您的回答，谢谢大佬

大漠工具内置了获取进程句柄的工具，可以参考这篇文章的第三章：
https://blog.csdn.net/weixin_45423515/article/details/125324841

**Comment by HelloBush** [comment]
> 期望您的回答，谢谢大佬

大漠工具内置了获取进程句柄的工具，可以参考这篇文章的第三章：
https://blog.csdn.net/weixin_45423515/article/details/125324841

**Comment by cwj24h** [comment]
已解决，谢谢大佬。大佬，能否留个联系方式，方便进行技术探讨。

**Comment by cwj24h** [comment]
感谢大佬的解答
