### ISSUE TITLE
按钮定位和图片识别问题

### ISSUE THREAD

**Issue by ljp1314258** [HelloBush/Java_MHXYdemo#6]
略微的看了下代码 坐标是写死的 我想应该有办法通过提前截图然后对比当前屏幕截图大图找小图获取坐标 移动鼠标到指定坐标然后点击吧

**Comment by HelloBush** [comment]
对，这个也是下一步我准备写的方向，现在的只是一个初步demo，用来测试一下Java写脚本，后面有考虑用图片匹配，比如比较汉明距离，特征值之类的办法来实现找图。此外，由于是游戏，界面都是比较固定的 ，可以利用相对位置，计算游戏界面整体面积，然后计算目标图片整体面积，以及目标图片在当前游戏面积内的左上角的相对位置，从而缩小找图范围，只去相对位置往外扩散一定范围的区域内找图，提高查找效率并且后序移植到其它电脑上也可以通过设置一个偏移误差来保证匹配。

不过目前生活上有些事要处理，得等月底再更新了。

**Comment by HelloBush** [comment]
> 略微的看了下代码 坐标是写死的 我想应该有办法通过提前截图然后对比当前屏幕截图大图找小图获取坐标 移动鼠标到指定坐标然后点击吧 

对，这个也是下一步我准备写的方向，现在的只是一个初步demo，用来测试一下Java写脚本，后面有考虑用图片匹配，比如比较汉明距离，特征值之类的办法来实现找图。此外，由于是游戏，界面都是比较固定的 ，可以利用相对位置，计算游戏界面整体面积，然后计算目标图片整体面积，以及目标图片在当前游戏面积内的左上角的相对位置，从而缩小找图范围，只去相对位置往外扩散一定范围的区域内找图，提高查找效率并且后序移植到其它电脑上也可以通过设置一个偏移误差来保证匹配。

不过目前生活上有些事要处理，得等月底再更新了。

**Comment by HelloBush** [comment]
已经利用OpenCV在java中实现特征匹配
