### ISSUE TITLE
你好，想学习下，这个怎么打包运行到android里？？

### ISSUE THREAD

**Issue by sunsou1** [HelloBush/Java_MHXYdemo#7]
这边也想学习下，希望有时间可以回复下

**Comment by HelloBush** [comment]
直接打包到安卓里面是运行不了的。

项目测试用的是梦幻西游的桌面版，在windows环境下运行的，手机上用的话游戏的句柄得你自己用其它办法获取，但Java图色识别部分的代码都是相同的，可以参考一下。
